version: "3.6"
services:
    web-server:
        build:
            context: .
            args:
               NODE_ENV: production
        environment:
           - NODE_ENV=production
        command: node server.js